# Generated by Django 2.2.4 on 2019-08-13 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(choices=[('http://127.0.0.1:8000/landing1/', 'http://127.0.0.1:8000/landing1/'), ('http://127.0.0.1:8000/landing2/', 'http://127.0.0.1:8000/landing2/'), ('http://127.0.0.1:8000/landing3/', 'http://127.0.0.1:8000/landing3/')])),
                ('name', models.CharField(max_length=256)),
                ('weight', models.IntegerField()),
                ('allowed_countries', django_countries.fields.CountryField(max_length=746, multiple=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('short_url_path', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='url_manager.Link')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LinksLandingPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url_manager.LandingPage')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url_manager.Link')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='url_manager.Profile'),
        ),
    ]
