# Generated by Django 2.2.4 on 2019-08-13 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('url_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='url_manager.Link'),
        ),
    ]
