# Generated by Django 2.2.4 on 2019-08-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_manager', '0002_auto_20190813_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=256, primary_key=True, serialize=False)),
        ),
    ]
